"""Add brand_name column in Brand Table

Revision ID: 0ac24bf6e59f
Revises: 1da8ca77cfff
Create Date: 2026-03-28 23:28:47.312684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ac24bf6e59f'
down_revision: Union[str, Sequence[str], None] = '1da8ca77cfff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brands', sa.Column('brand_name', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'brands', ['brand_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'brands', type_='unique')
    op.drop_column('brands', 'brand_name')
    # ### end Alembic commands ###
