"""Add user and addresses relationship

Revision ID: 1da8ca77cfff
Revises: 4e0f608d05bd
Create Date: 2026-03-15 21:06:51.778058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1da8ca77cfff'
down_revision: Union[str, Sequence[str], None] = '4e0f608d05bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('user_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'addresses', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'addresses', type_='foreignkey')
    op.drop_column('addresses', 'user_id')
    # ### end Alembic commands ###
