"""Add unique constraint from favorite model

Revision ID: 21efeb46aa8b
Revises: 758af7b25926
Create Date: 2026-04-20 19:51:10.098149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21efeb46aa8b'
down_revision: Union[str, Sequence[str], None] = '758af7b25926'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_product_favorite', 'favorites', ['user_id', 'product_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_product_favorite', 'favorites', type_='unique')
    # ### end Alembic commands ###
