"""Fix avg_grade in Product table

Revision ID: 238c433bb9b3
Revises: 0ac24bf6e59f
Create Date: 2026-03-29 07:00:59.476343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '238c433bb9b3'
down_revision: Union[str, Sequence[str], None] = '0ac24bf6e59f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'avg_grade',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'avg_grade',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
