"""Change logic for m:m orders carts sizes product relationships

Revision ID: 2aefbb6d98f3
Revises: 750094f48e40
Create Date: 2026-04-04 00:31:38.400079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2aefbb6d98f3'
down_revision: Union[str, Sequence[str], None] = '750094f48e40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cartitems', sa.Column('sizes_id', sa.String(), nullable=False))
    op.drop_constraint(op.f('idx_unique_cart_product'), 'cartitems', type_='unique')
    op.create_unique_constraint('idx_unique_cart_product', 'cartitems', ['cart_id', 'sizes_id'])
    op.drop_constraint(op.f('cartitems_product_id_fkey'), 'cartitems', type_='foreignkey')
    op.create_foreign_key(None, 'cartitems', 'sizes', ['sizes_id'], ['id'])
    op.drop_column('cartitems', 'product_id')
    op.add_column('orderitems', sa.Column('sizes_id', sa.String(), nullable=False))
    op.drop_constraint(op.f('idx_unique_order_product'), 'orderitems', type_='unique')
    op.create_unique_constraint('idx_unique_order_product', 'orderitems', ['order_id', 'sizes_id'])
    op.drop_constraint(op.f('orderitems_product_id_fkey'), 'orderitems', type_='foreignkey')
    op.create_foreign_key(None, 'orderitems', 'sizes', ['sizes_id'], ['id'])
    op.drop_column('orderitems', 'product_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orderitems', sa.Column('product_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'orderitems', type_='foreignkey')
    op.create_foreign_key(op.f('orderitems_product_id_fkey'), 'orderitems', 'products', ['product_id'], ['id'])
    op.drop_constraint('idx_unique_order_product', 'orderitems', type_='unique')
    op.create_unique_constraint(op.f('idx_unique_order_product'), 'orderitems', ['order_id', 'product_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('orderitems', 'sizes_id')
    op.add_column('cartitems', sa.Column('product_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'cartitems', type_='foreignkey')
    op.create_foreign_key(op.f('cartitems_product_id_fkey'), 'cartitems', 'products', ['product_id'], ['id'])
    op.drop_constraint('idx_unique_cart_product', 'cartitems', type_='unique')
    op.create_unique_constraint(op.f('idx_unique_cart_product'), 'cartitems', ['cart_id', 'product_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('cartitems', 'sizes_id')
    # ### end Alembic commands ###
