"""Update models

Revision ID: 4e0f608d05bd
Revises: d02fc9ecdd53
Create Date: 2026-03-09 01:25:35.441067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e0f608d05bd'
down_revision: Union[str, Sequence[str], None] = 'd02fc9ecdd53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('brands_product_id_fkey'), 'brands', type_='foreignkey')
    op.drop_column('brands', 'product_id')
    op.add_column('products', sa.Column('brand_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'products', 'brands', ['brand_id'], ['id'])
    op.alter_column('users', 'social_link',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'social_link',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'brand_id')
    op.add_column('brands', sa.Column('product_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('brands_product_id_fkey'), 'brands', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###
