"""Enum migration

Revision ID: 56c25c461aa7
Revises: fe7c9b5d16d3
Create Date: 2026-04-07 19:36:10.813920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56c25c461aa7'
down_revision: Union[str, Sequence[str], None] = 'fe7c9b5d16d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('size_39', 'size_40', 'size_41', 'size_42', 'size_43', 'size_44', 'size_45', name='asizes').create(op.get_bind())
    sa.Enum('running', 'everyday', 'basketball', 'training', name='category').create(op.get_bind())
    op.alter_column('products', 'category',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('running', 'everyday', 'basketball', 'training', name='category'),
               existing_nullable=False,
               postgresql_using='category::category')
    op.alter_column('sizes', 'size',
               existing_type=sa.INTEGER(),
               type_=sa.Enum('size_39', 'size_40', 'size_41', 'size_42', 'size_43', 'size_44', 'size_45', name='asizes'),
               existing_nullable=False,
               postgresql_using="size::text::asizes")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sizes', 'size',
               existing_type=sa.Enum('size_39', 'size_40', 'size_41', 'size_42', 'size_43', 'size_44', 'size_45', name='asizes'),
               type_=sa.INTEGER(),
               postgresql_using="size::text::asizes",
               existing_nullable=False)
    op.alter_column('products', 'category',
               existing_type=sa.Enum('running', 'everyday', 'basketball', 'training', name='category'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    sa.Enum('running', 'everyday', 'basketball', 'training', name='category').drop(op.get_bind())
    sa.Enum('size_39', 'size_40', 'size_41', 'size_42', 'size_43', 'size_44', 'size_45', name='asizes').drop(op.get_bind())
    # ### end Alembic commands ###
