"""Update forgein key cascade

Revision ID: 6b4669f5d750
Revises: e9d179f8da4c
Create Date: 2026-04-04 05:21:50.482358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b4669f5d750'
down_revision: Union[str, Sequence[str], None] = 'e9d179f8da4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('addresses_user_id_fkey'), 'addresses', type_='foreignkey')
    op.create_foreign_key(None, 'addresses', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(op.f('cartitems_size_id_fkey'), 'cartitems', type_='foreignkey')
    op.drop_constraint(op.f('cartitems_cart_id_fkey'), 'cartitems', type_='foreignkey')
    op.create_foreign_key(None, 'cartitems', 'sizes', ['size_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(None, 'cartitems', 'carts', ['cart_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_constraint(op.f('carts_user_id_fkey'), 'carts', type_='foreignkey')
    op.create_foreign_key(None, 'carts', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(op.f('favorites_product_id_fkey'), 'favorites', type_='foreignkey')
    op.drop_constraint(op.f('favorites_user_id_fkey'), 'favorites', type_='foreignkey')
    op.create_foreign_key(None, 'favorites', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'favorites', 'products', ['product_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(op.f('orderitems_size_id_fkey'), 'orderitems', type_='foreignkey')
    op.drop_constraint(op.f('orderitems_order_id_fkey'), 'orderitems', type_='foreignkey')
    op.create_foreign_key(None, 'orderitems', 'orders', ['order_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(None, 'orderitems', 'sizes', ['size_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_constraint(op.f('orders_user_id_fkey'), 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(op.f('reviews_user_id_fkey'), 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(op.f('sizes_product_id_fkey'), 'sizes', type_='foreignkey')
    op.create_foreign_key(None, 'sizes', 'products', ['product_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sizes', type_='foreignkey')
    op.create_foreign_key(op.f('sizes_product_id_fkey'), 'sizes', 'products', ['product_id'], ['id'])
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key(op.f('reviews_user_id_fkey'), 'reviews', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('orders_user_id_fkey'), 'orders', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'orderitems', type_='foreignkey')
    op.drop_constraint(None, 'orderitems', type_='foreignkey')
    op.create_foreign_key(op.f('orderitems_order_id_fkey'), 'orderitems', 'orders', ['order_id'], ['id'])
    op.create_foreign_key(op.f('orderitems_size_id_fkey'), 'orderitems', 'sizes', ['size_id'], ['id'])
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.create_foreign_key(op.f('favorites_user_id_fkey'), 'favorites', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('favorites_product_id_fkey'), 'favorites', 'products', ['product_id'], ['id'])
    op.drop_constraint(None, 'carts', type_='foreignkey')
    op.create_foreign_key(op.f('carts_user_id_fkey'), 'carts', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'cartitems', type_='foreignkey')
    op.drop_constraint(None, 'cartitems', type_='foreignkey')
    op.create_foreign_key(op.f('cartitems_cart_id_fkey'), 'cartitems', 'carts', ['cart_id'], ['id'])
    op.create_foreign_key(op.f('cartitems_size_id_fkey'), 'cartitems', 'sizes', ['size_id'], ['id'])
    op.drop_constraint(None, 'addresses', type_='foreignkey')
    op.create_foreign_key(op.f('addresses_user_id_fkey'), 'addresses', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
