"""Base Init

Revision ID: 758af7b25926
Revises: 
Create Date: 2026-04-14 13:12:27.212852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '758af7b25926'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('39', '40', '41', '42', '43', '44', '45', name='asizes').create(op.get_bind())
    sa.Enum('running', 'everyday', 'basketball', 'training', name='category').create(op.get_bind())
    sa.Enum('black', 'white', 'red', 'orange', 'yellow', 'green', 'light_blue', 'blue', 'purple', name='color').create(op.get_bind())
    sa.Enum('confirmation', 'transit', 'delivered', 'cancelled', name='status').create(op.get_bind())
    sa.Enum('user', 'admin', name='role').create(op.get_bind())
    op.create_table('brands',
    sa.Column('brand_name', sa.String(), nullable=False),
    sa.Column('brand_logo', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_name')
    )
    op.create_table('users',
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('patronymic', sa.String(), nullable=False),
    sa.Column('password', sa.LargeBinary(), nullable=False),
    sa.Column('social_link', sa.String(), nullable=False),
    sa.Column('role', postgresql.ENUM('user', 'admin', name='role', create_type=False), server_default=sa.text("'user'"), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('addresses',
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('street', sa.String(), nullable=False),
    sa.Column('house', sa.String(), nullable=False),
    sa.Column('entrance', sa.String(), nullable=False),
    sa.Column('apartment', sa.String(), nullable=False),
    sa.Column('postcode', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carts',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('products',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('color', postgresql.ENUM('black', 'white', 'red', 'orange', 'yellow', 'green', 'light_blue', 'blue', 'purple', name='color', create_type=False), nullable=False),
    sa.Column('logo', sa.String(), nullable=True),
    sa.Column('article', sa.String(), nullable=False),
    sa.Column('category', postgresql.ENUM('running', 'everyday', 'basketball', 'training', name='category', create_type=False), nullable=False),
    sa.Column('avg_grade', sa.Float(), nullable=False),
    sa.Column('brand_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('comment_text', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), server_default='5', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorites',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('order_date', sa.DateTime(), nullable=False),
    sa.Column('total_amount', sa.Integer(), nullable=False),
    sa.Column('status', postgresql.ENUM('confirmation', 'transit', 'delivered', 'cancelled', name='status', create_type=False), server_default=sa.text("'confirmation'"), nullable=False),
    sa.Column('address_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sizes',
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('size', postgresql.ENUM('39', '40', '41', '42', '43', '44', '45', name='asizes', create_type=False), server_default='39', nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cartitems',
    sa.Column('cart_id', sa.String(), nullable=False),
    sa.Column('size_id', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['size_id'], ['sizes.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cart_id', 'size_id', name='idx_unique_cart_product')
    )
    op.create_table('orderitems',
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('size_id', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['size_id'], ['sizes.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'size_id', name='idx_unique_order_product')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orderitems')
    op.drop_table('cartitems')
    op.drop_table('sizes')
    op.drop_table('orders')
    op.drop_table('favorites')
    op.drop_table('reviews')
    op.drop_table('products')
    op.drop_table('carts')
    op.drop_table('addresses')
    op.drop_table('users')
    op.drop_table('brands')
    sa.Enum('user', 'admin', name='role').drop(op.get_bind())
    sa.Enum('confirmation', 'transit', 'delivered', 'cancelled', name='status').drop(op.get_bind())
    sa.Enum('black', 'white', 'red', 'orange', 'yellow', 'green', 'light_blue', 'blue', 'purple', name='color').drop(op.get_bind())
    sa.Enum('running', 'everyday', 'basketball', 'training', name='category').drop(op.get_bind())
    sa.Enum('39', '40', '41', '42', '43', '44', '45', name='asizes').drop(op.get_bind())
    # ### end Alembic commands ###
