"""Add column 'article' in product table

Revision ID: 85789fd537ab
Revises: db723bd26a76
Create Date: 2026-04-04 19:40:48.315375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85789fd537ab'
down_revision: Union[str, Sequence[str], None] = 'db723bd26a76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('article', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'article')
    # ### end Alembic commands ###
