"""update_color_enum

Revision ID: c669a23acc85
Revises: 43b1985f7ce2
Create Date: 2026-04-06 21:34:05.177434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = 'c669a23acc85'
down_revision: Union[str, Sequence[str], None] = '43b1985f7ce2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='color',
        new_values=['black', 'white', 'red', 'orange', 'yellow', 'green', 'light_blue', 'blue', 'purple'],
        affected_columns=[TableReference(table_schema='public', table_name='products', column_name='color')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='color',
        new_values=['black', 'white', 'blue', 'gray'],
        affected_columns=[TableReference(table_schema='public', table_name='products', column_name='color')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
