"""Add M:M relationships between Cart, Order and Product tables

Revision ID: d02fc9ecdd53
Revises: 88ceed845e04
Create Date: 2026-03-03 20:56:52.602612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd02fc9ecdd53'
down_revision: Union[str, Sequence[str], None] = '88ceed845e04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cartitems',
    sa.Column('cart_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cart_id', 'product_id', name='idx_unique_cart_product')
    )
    op.create_table('orderitems',
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'product_id', name='idx_unique_order_product')
    )
    op.drop_constraint(op.f('addresses_order_id_fkey'), 'addresses', type_='foreignkey')
    op.drop_column('addresses', 'order_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('order_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('addresses_order_id_fkey'), 'addresses', 'orders', ['order_id'], ['id'])
    op.drop_table('orderitems')
    op.drop_table('cartitems')
    # ### end Alembic commands ###
