"""Add column 'logo' in product table

Revision ID: db723bd26a76
Revises: 6b4669f5d750
Create Date: 2026-04-04 05:28:49.570375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db723bd26a76'
down_revision: Union[str, Sequence[str], None] = '6b4669f5d750'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('logo', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'logo')
    # ### end Alembic commands ###
