"""Fix name for association columns

Revision ID: e9d179f8da4c
Revises: 2aefbb6d98f3
Create Date: 2026-04-04 04:18:04.849466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9d179f8da4c'
down_revision: Union[str, Sequence[str], None] = '2aefbb6d98f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cartitems', sa.Column('size_id', sa.String(), nullable=False))
    op.drop_constraint(op.f('idx_unique_cart_product'), 'cartitems', type_='unique')
    op.create_unique_constraint('idx_unique_cart_product', 'cartitems', ['cart_id', 'size_id'])
    op.drop_constraint(op.f('cartitems_sizes_id_fkey'), 'cartitems', type_='foreignkey')
    op.create_foreign_key(None, 'cartitems', 'sizes', ['size_id'], ['id'])
    op.drop_column('cartitems', 'sizes_id')
    op.add_column('orderitems', sa.Column('size_id', sa.String(), nullable=False))
    op.drop_constraint(op.f('idx_unique_order_product'), 'orderitems', type_='unique')
    op.create_unique_constraint('idx_unique_order_product', 'orderitems', ['order_id', 'size_id'])
    op.drop_constraint(op.f('orderitems_sizes_id_fkey'), 'orderitems', type_='foreignkey')
    op.create_foreign_key(None, 'orderitems', 'sizes', ['size_id'], ['id'])
    op.drop_column('orderitems', 'sizes_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orderitems', sa.Column('sizes_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'orderitems', type_='foreignkey')
    op.create_foreign_key(op.f('orderitems_sizes_id_fkey'), 'orderitems', 'sizes', ['sizes_id'], ['id'])
    op.drop_constraint('idx_unique_order_product', 'orderitems', type_='unique')
    op.create_unique_constraint(op.f('idx_unique_order_product'), 'orderitems', ['order_id', 'sizes_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('orderitems', 'size_id')
    op.add_column('cartitems', sa.Column('sizes_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'cartitems', type_='foreignkey')
    op.create_foreign_key(op.f('cartitems_sizes_id_fkey'), 'cartitems', 'sizes', ['sizes_id'], ['id'])
    op.drop_constraint('idx_unique_cart_product', 'cartitems', type_='unique')
    op.create_unique_constraint(op.f('idx_unique_cart_product'), 'cartitems', ['cart_id', 'sizes_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('cartitems', 'size_id')
    # ### end Alembic commands ###
