"""Add new column category in product table, Fix avg_grade

Revision ID: fe7c9b5d16d3
Revises: 7b46a1ee2eb3
Create Date: 2026-04-07 18:49:27.469775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe7c9b5d16d3'
down_revision: Union[str, Sequence[str], None] = '7b46a1ee2eb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('category', sa.String(), nullable=False))
    op.alter_column('products', 'avg_grade',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'avg_grade',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('products', 'category')
    # ### end Alembic commands ###
